version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ins_collector_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ins_network

  redis:
    image: redis:7-alpine
    container_name: ins_collector_redis
    ports:
      - "6379:6379"
    networks:
      - ins_network

  backend:
    build: ./backend
    container_name: ins_collector_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - DEBUG=${DEBUG}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - ins_network

  frontend:
    build: ./frontend
    container_name: ins_collector_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - ins_network

volumes:
  postgres_data:

networks:
  ins_network:
    driver: bridge